### ISSUE TITLE
Form Ownership

### ISSUE THREAD

**Issue by abhishekpradhan** [shayan786/hike-it#2]

**Comment by shayan786** [comment]
I can take care of the front-end + design intro, then we can all iterate, i say @abhishekpradhan takes more of a lead on the backend (i'll support). @hanxu27 comes up with the user stories / requirements + tester (i'll help you out here)

**Comment by hanxu27** [comment]
@shayan786 can I tag along for the design intro? I would like to understand the product a little more.

**Comment by shayan786** [comment]
@hanxu27 ofcourse 👍 

Process for me really is:
- What is the point of the app
- Break down into our user (persona)
- Come up with some 'stories' for that user and what they will do
- Scope down certain stories and label as 'MVP'
- Break down those even more into smaller achievable tasks.
- Start mockups
- Build & Iterate

**Comment by hanxu27** [comment]
@shayan786 was the first three bullets already talked about?

**Comment by shayan786** [comment]
@hanxu27 nope, nothing has been yet ... you can create some issues for them / whatever else you feel like is important and we can talk about it there.
