### ISSUE TITLE
Goal of App

### ISSUE THREAD

**Issue by hanxu27** [shayan786/hike-it#7]
Some features:
Map, navigation
Finding parking areas
Planning and coordinating with friends
Trail history and specs
Showing off in social media
Collage

Our target users should be young adults that likes outdoor activities.

Anyone has any thoughts?

**Comment by shayan786** [comment]
This is good @hanxu27, lets add some more detail: 
- Map - _of? how to get there or the trail or both_
- Navigation - _of? how to get there or the trail or both_
- Parking - _agree, but lets go more granular_
- Planning / Cordinating - _via? text, builtin, fb etc?_
- Trails History & Specs - _lets get into exactly what those are, prob want to add reviews_
- Sharing - _more detail, just a pic on fb or more than that or just redirect etc etc_
- Collage - _sure, but i would put this as nice to have but def. not mvp_

Target Users - _i think it can be more general than just young adults, possibly anyone who wants to hike_

I like, good job @hanxu27

**Comment by hanxu27** [comment]
For target users, I specifically narrowed down the young adults because they are the early adopters for new apps. If we look at other populations who goes on hikes, I have them pinned as more conservative and less tech savvy, which would translate to hard to get new users.  

In my mind there are three areas the main feature can be:
1. Serving as a tour guide
2. Helping in coordinating the events
3. Sharing across social media

My thoughts on each idea.
1. People who likes hiking doesn't want to have their phones out all the time. From a practical aspect lot's of trails have bad reception so that would make the app more complex.
2. Too many competitors, between meetup, facebook events, and sharing calendar, I feel like it would to narrow of a focus having a schedule app just for hiking.
3. This is the only one I can picture succeeding. Basically the running app (shows your route/time) combined with instagram. It would post the trail map combined with a few pictures from the hike combined in a collage.

These are my thoughts so far. Feel free to jump in.

**Comment by shayan786** [comment]
3 from above i think is pretty low in priority i think.

My ranking in order:
- Trail info (define what that is the hike, map, time, difficulty etc.) <-- this one has alot of challenges
- Sharing
- Sharing -> creating a collage.
